![](https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/IOC_Logo.svg/2341px-IOC_Logo.svg.png)

# Introduction

Welcome to your first day as an analyst working for the IOC! The IOC is at the very heart of world sport, supporting every Olympic Movement stakeholder, promoting Olympism worldwide, and overseeing the regular celebration of the Olympic Games.

For a moment of glory on the medalist podium, elite athletes dedicate *everything* to their sport. Olympics medalists from 1896 through 2016 comprise the dataset you'll be working with. Who are the youngest and oldest medalists of all time? Are there physical differences between Summer Olympics medalists and Winter Olympics medalists? You're about to use your data coding chops to find out!

You'll start this Milestone assignment by cleaning and filtering the data. So many of your Python skills that you've learned so far will be at play. Are you up for it? Let's go! 

### Dataset Description

The dataset is stored in a .csv file named `olympics.csv`. It contains the following columns:

* **ID**: A unique identifying number of each athlete
* **Name**: The name of each athlete
* **Sex**: M or F
* **Age**: The age of an athlete, in years, at the time they competed.
* **Height**: The height of an athlete, in centimeters
* **Weight**: The weight of an athlete, in kilograms
* **Team**: The name of the athlete’s team. Not always the name of a country.
* **NOC**: National Olympic Committee’s 3 letter code
* **Games**: Year and season
* **Season**: Summer or Winter
* **City**: Host city
* **Sport**: The sport or category of an olympic event/activity
* **Event**: specific event within a sport, e.g. Men’s 400 meters breaststroke.
* **Medal**: Gold, Silver, Bronze
* **Region**: Name of athlete’s country

# Task 1: Data Inspection

![](https://media.giphy.com/media/42wQXwITfQbDGKqUP7/giphy.gif)

In [1]:
# import the pandas library
import pandas as pd

In [2]:
# Load in the data
df = pd.read_csv('datasets/olympics.csv')

In [3]:
# Preview DataFrame
df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region
0,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark
1,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 200 metres Breaststroke,Bronze,Finland
2,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 400 metres Breaststroke,Bronze,Finland
3,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,Finland
4,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Individual All-Around,Bronze,Finland

In [4]:
# Inspect the numbers of rows and columns
df.shape

(39783, 16)

In [5]:
# Inspect column names
df.columns

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal', 'region'],
      dtype='object')

In [6]:
# Inspect column data types, memory usage, etc.
df.info

<bound method DataFrame.info of            ID                                 Name Sex   Age  Height  Weight  \
0           4                 Edgar Lindenau Aabye   M  34.0     NaN     NaN
1          15                 Arvo Ossian Aaltonen   M  30.0     NaN     NaN
2          15                 Arvo Ossian Aaltonen   M  30.0     NaN     NaN
3          16             Juhamatti Tapio Aaltonen   M  28.0   184.0    85.0
4          17              Paavo Johannes Aaltonen   M  28.0   175.0    64.0
...       ...                                  ...  ..   ...     ...     ...
39778  135553  Galina Ivanovna Zybina (-Fyodorova)   F  25.0   168.0    80.0
39779  135553  Galina Ivanovna Zybina (-Fyodorova)   F  33.0   168.0    80.0
39780  135554                         Bogusaw Zych   M  28.0   182.0    82.0
39781  135563            Olesya Nikolayevna Zykina   F  19.0   171.0    64.0
39782  135563            Olesya Nikolayevna Zykina   F  23.0   171.0    64.0

                 Team  NOC        Games  Year  Season       City       Sport  \
0      Denmark/Sweden  DEN  1900 Summer  1900  Summer      Paris  Tug-Of-War
1             Finland  FIN  1920 Summer  1920  Summer  Antwerpen    Swimming
2             Finland  FIN  1920 Summer  1920  Summer  Antwerpen    Swimming
3             Finland  FIN  2014 Winter  2014  Winter      Sochi  Ice Hockey
4             Finland  FIN  1948 Summer  1948  Summer     London  Gymnastics
...               ...  ...          ...   ...     ...        ...         ...
39778    Soviet Union  URS  1956 Summer  1956  Summer  Melbourne   Athletics
39779    Soviet Union  URS  1964 Summer  1964  Summer      Tokyo   Athletics
39780          Poland  POL  1980 Summer  1980  Summer     Moskva     Fencing
39781          Russia  RUS  2000 Summer  2000  Summer     Sydney   Athletics
39782          Russia  RUS  2004 Summer  2004  Summer     Athina   Athletics

                                        Event   Medal   region
0                 Tug-Of-War Men's Tug-Of-War    Gold  Denmark
1      Swimming Men's 200 metres Breaststroke  Bronze  Finland
2      Swimming Men's 400 metres Breaststroke  Bronze  Finland
3                 Ice Hockey Men's Ice Hockey  Bronze  Finland
4      Gymnastics Men's Individual All-Around  Bronze  Finland
...                                       ...     ...      ...
39778              Athletics Women's Shot Put  Silver   Russia
39779              Athletics Women's Shot Put  Bronze   Russia
39780                Fencing Men's Foil, Team  Bronze   Poland
39781  Athletics Women's 4 x 400 metres Relay  Bronze   Russia
39782  Athletics Women's 4 x 400 metres Relay  Silver   Russia

[39783 rows x 16 columns]>

In [7]:
# Display a statistcial summary of the data
df.describe()

                  ID           Age        Height        Weight          Year
count   39783.000000  39051.000000  31072.000000  30456.000000  39783.000000
mean    69407.051806     25.925175    177.554197     73.770680   1973.943845
std     38849.980737      5.914026     10.893723     15.016025     33.822857
min         4.000000     10.000000    136.000000     28.000000   1896.000000
25%     36494.000000     22.000000    170.000000     63.000000   1952.000000
50%     68990.000000     25.000000    178.000000     73.000000   1984.000000
75%    103461.500000     29.000000    185.000000     83.000000   2002.000000
max    135563.000000     73.000000    223.000000    182.000000   2016.000000

In [9]:
# What types of medals are there?
tmedal = df['Medal'].unique()
print(tmedal)

['Gold' 'Bronze' 'Silver']

# Task 2: Data Cleaning

![](https://media.giphy.com/media/10zsjaH4g0GgmY/giphy.gif)

In [11]:
# Rename 'NOC' column to 'CountryCode'
# Rename 'region' column to 'Country'
column_to_rename = {
    'NOC':'CountryCode', 'region':'Country'
}
df.rename(columns = column_to_rename)

,ID,Name,Sex,Age,Height,Weight,Team,CountryCode,Games,Year,Season,City,Sport,Event,Medal,Country
0,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark
1,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 200 metres Breaststroke,Bronze,Finland
2,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,Finland,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 400 metres Breaststroke,Bronze,Finland
3,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,Finland
4,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Individual All-Around,Bronze,Finland
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39778,135553,Galina Ivanovna Zybina (-Fyodorova),F,25.0,168.0,80.0,Soviet Union,URS,1956 Summer,1956,Summer,Melbourne,Athletics,Athletics Women's Shot Put,Silver,Russia
39779,135553,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union,URS,1964 Summer,1964,Summer,Tokyo,Athletics,Athletics Women's Shot Put,Bronze,Russia
39780,135554,Bogusaw Zych,M,28.0,182.0,82.0,Poland,POL,1980 Summer,1980,Summer,Moskva,Fencing,"Fencing Men's Foil, Team",Bronze,Poland
39781,135563,Olesya Nikolayevna Zykina,F,19.0,171.0,64.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Athletics,Athletics Women's 4 x 400 metres Relay,Bronze,Russia
39782,135563,Olesya Nikolayevna Zykina,F,23.0,171.0,64.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Athletics,Athletics Women's 4 x 400 metres Relay,Silver,Russia

In [14]:
# Remove the 'Team' column
cols_to_remove = ["Team"]
df2 = df.drop(columns = cols_to_remove)
df2.head()

,ID,Name,Sex,Age,Height,Weight,NOC,Games,Year,Season,City,Sport,Event,Medal,region
0,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark
1,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 200 metres Breaststroke,Bronze,Finland
2,15,Arvo Ossian Aaltonen,M,30.0,NaN,NaN,FIN,1920 Summer,1920,Summer,Antwerpen,Swimming,Swimming Men's 400 metres Breaststroke,Bronze,Finland
3,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,FIN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,Finland
4,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,FIN,1948 Summer,1948,Summer,London,Gymnastics,Gymnastics Men's Individual All-Around,Bronze,Finland

# Task 3: Data Analysis

![](https://media.giphy.com/media/MT5UUV1d4CXE2A37Dg/giphy.gif)

In [21]:
# What is the youngest age of an Olympics medalist?
df.sort_values(by = ['Age'], ascending = True).head()
#The youngest Olympic Medalist is 10 years old

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region
20753,71691,Dimitrios Loundras,M,10.0,NaN,NaN,Ethnikos Gymnastikos Syllogos,GRE,1896 Summer,1896,Summer,Athina,Gymnastics,"Gymnastics Men's Parallel Bars, Teams",Bronze,Greece
11021,40129,Luigina Giavotti,F,11.0,NaN,NaN,Italy,ITA,1928 Summer,1928,Summer,Amsterdam,Gymnastics,Gymnastics Women's Team All-Around,Silver,Italy
36402,125092,tienne Nol Henri Vandernotte,M,12.0,NaN,37.0,France,FRA,1936 Summer,1936,Summer,Berlin,Rowing,Rowing Men's Coxed Pairs,Bronze,France
36403,125092,tienne Nol Henri Vandernotte,M,12.0,NaN,37.0,France,FRA,1936 Summer,1936,Summer,Berlin,Rowing,Rowing Men's Coxed Fours,Bronze,France
36617,125944,Ines Vercesi,F,12.0,NaN,NaN,Italy,ITA,1928 Summer,1928,Summer,Amsterdam,Gymnastics,Gymnastics Women's Team All-Around,Silver,Italy

In [24]:
# What is the oldest age of an Olympics medalist?
df.sort_values(by = ['Age'], ascending = False).head()
#The Oldest Olympic Medalist is 73 years old

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region
6072,22984,John (Herbert Crawford-) Copley (Williamson-),M,73.0,NaN,NaN,Great Britain,GBR,1948 Summer,1948,Summer,London,Art Competitions,"Art Competitions Mixed Painting, Graphic Arts",Silver,UK
8279,30731,Jozu Dupon,M,72.0,NaN,NaN,Belgium,BEL,1936 Summer,1936,Summer,Berlin,Art Competitions,"Art Competitions Mixed Sculpturing, Medals",Bronze,Belgium
33952,117046,Oscar Gomer Swahn,M,72.0,NaN,NaN,Sweden,SWE,1920 Summer,1920,Summer,Antwerpen,Shooting,"Shooting Men's Running Target, Double Shot, Team",Silver,Sweden
21901,75648,Charles William Martin,M,71.0,NaN,NaN,Crabe II-1,FRA,1900 Summer,1900,Summer,Paris,Sailing,Sailing Mixed 0.5-1 Ton,Silver,France
21902,75648,Charles William Martin,M,71.0,NaN,NaN,Crabe II-4,FRA,1900 Summer,1900,Summer,Paris,Sailing,Sailing Mixed 0.5-1 Ton,Bronze,France

In [31]:
# How many of each medal were awarded?
df['Medal'].value_counts()
#there are 13,371 gold medals, 13295 bronze medals, and 13116 Silver Medals

Gold      13372
Bronze    13295
Silver    13116
Name: Medal, dtype: int64

In [36]:
# How many events are there?
df['Event'].nunique()
#756 Events

756

In [37]:
# How many sports are there?
df['Sport'].nunique()
#66 Sports

66

In [38]:
# What is the average age of an Olympics medalist?
df['Age'].mean()

25.925174771452717

In [49]:
# Among the 10 oldest medalists, what are the most common sports?
df2 = df.sort_values(by = ['Age'], ascending = False)
top_10_ages = df2.head(10)
most_common_sport = top_10_ages['Sport'].value_counts()
most_common_sport

#Art Competitions are the most common sport amongst old people

Art Competitions    5
Sailing             3
Shooting            1
Archery             1
Name: Sport, dtype: int64

In [64]:
# What are the 10 winningest countries in total medal count?
df2 = df.sort_values(by = 'Medal',ascending = False)
df2_top_10 = df2.head(10)
winning_countries = df2_top_10['region'].value_counts()
winning_countries

Switzerland    4
Finland        4
Poland         1
China          1
Name: region, dtype: int64

In [82]:
# How many medals have been awarded in the sport of trampolining?
df2 = (df['Sport'] == 'Trampolining')
df2.count()

39783

# Level Up

![](https://media.giphy.com/media/YYaapBJ7UAZp9DJS7o/giphy.gif)

Want to Level Up your practice? We love to see it! Take a crack at some of these extra challenges, including visualizing some of this here data.

In [ ]:
# How many gold medals were awarded to the United States?

In [ ]:
# List the Olympics in dataset, starting with the most recent

In [ ]:
# Average medalist height in the most recent Winter Olympics

In [ ]:
# Average medalist weight in the most recent Winter Olympics

In [ ]:
# Average medalist height in the most recent Summer Olympics

In [ ]:
# Average medalist weight in the most recent Summer Olympics

In [ ]:
# Import plotly express library

In [ ]:
# Asssign top 10 winningest countries table to a variable
# You did this in task 3

In [ ]:
# Visualize the table as a bar chart